// this can be used to map new fields

export const mockHeaders = [
  {
    title: '',
    data: 'Codigo',
    name: 'Codigo',
    width: '0%',
    widthDefault: '0%',
    orderable: false,
    visible: false,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 0,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Carga',
    data: 'NumeroCarga',
    name: 'NumeroCarga',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: true,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 1,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Pedido',
    data: 'Pedido',
    name: 'Pedido',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: true,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 2,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Data Pedido',
    data: 'DataPedido',
    name: 'DataPedido',
    width: '1.0948905109489055%',
    widthDefault: '3%',
    orderable: true,
    visible: true,
    className: 'text-center',
    dateTimePattern: 'dd/MM/yyyy',
    tabletHide: false,
    phoneHide: false,
    position: 3,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Horário Pedido',
    data: 'HoraPedido',
    name: 'HoraPedido',
    width: '1.0948905109489055%',
    widthDefault: '3%',
    orderable: true,
    visible: true,
    className: 'text-center',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 4,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Peso Pedido',
    data: 'PesoPedido',
    name: 'PesoPedido',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: true,
    visible: true,
    className: 'text-end',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 5,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Valor Pedido',
    data: 'ValorPedido',
    name: 'ValorPedido',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: true,
    visible: true,
    className: 'text-end',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 6,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Data Carga',
    data: 'DataCarga',
    name: 'DataCarga',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: true,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 7,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Data Emissão CT-e',
    data: 'DataEmissaoFormatada',
    name: 'DataEmissaoFormatada',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: true,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 8,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Data Emissão NF-e',
    data: 'DataNotaFiscal',
    name: 'DataNotaFiscal',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: true,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 9,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Rota',
    data: 'Itinerario',
    name: 'Itinerario',
    width: '2.0072992700729935%',
    widthDefault: '5.5%',
    orderable: false,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 10,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Natureza NF',
    data: 'NaturezaNF',
    name: 'NaturezaNF',
    width: '1.0948905109489055%',
    widthDefault: '3%',
    orderable: true,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 11,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Filial',
    data: 'Filial',
    name: 'Filial',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: true,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 12,
    sumary: 0,
    enableGroup: true,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Tipo de Operação',
    data: 'TipoOperacao',
    name: 'TipoOperacao',
    width: '1.0948905109489055%',
    widthDefault: '3%',
    orderable: true,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 13,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Tipo de Carga',
    data: 'TipoCarga',
    name: 'TipoCarga',
    width: '1.0948905109489055%',
    widthDefault: '3%',
    orderable: true,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 14,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Código Remetente',
    data: 'CodigoRemetente',
    name: 'CodigoRemetente',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: false,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 15,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'CNPJ Remetente',
    data: 'CNPJRemetente',
    name: 'CNPJRemetente',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: true,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 16,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Remetente',
    data: 'Remetente',
    name: 'Remetente',
    width: '2.0072992700729935%',
    widthDefault: '5.5%',
    orderable: true,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 17,
    sumary: 0,
    enableGroup: true,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Endereço Remetente',
    data: 'EnderecoRemetente',
    name: 'EnderecoRemetente',
    width: '2.0072992700729935%',
    widthDefault: '5.5%',
    orderable: false,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 18,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Grupo Remetente',
    data: 'GrupoRemetente',
    name: 'GrupoRemetente',
    width: '2.0072992700729935%',
    widthDefault: '5.5%',
    orderable: true,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 19,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Categoria Remetente',
    data: 'CategoriaRemetente',
    name: 'CategoriaRemetente',
    width: '2.0072992700729935%',
    widthDefault: '5.5%',
    orderable: true,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 20,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Código Destinatário',
    data: 'CodigoDestinatario',
    name: 'CodigoDestinatario',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: false,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 21,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'CNPJ Destinatário',
    data: 'CNPJDestinatario',
    name: 'CNPJDestinatario',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: true,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 22,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Destinatário',
    data: 'Destinatario',
    name: 'Destinatario',
    width: '2.0072992700729935%',
    widthDefault: '5.5%',
    orderable: true,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 23,
    sumary: 0,
    enableGroup: true,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Endereço Destinatário',
    data: 'EnderecoDestinatario',
    name: 'EnderecoDestinatario',
    width: '2.0072992700729935%',
    widthDefault: '5.5%',
    orderable: false,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 24,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Telefone Destinatário',
    data: 'TelefoneDestinatario',
    name: 'TelefoneDestinatario',
    width: '2.0072992700729935%',
    widthDefault: '5.5%',
    orderable: false,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 25,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'E-mail Destinatário',
    data: 'EmailDestinatario',
    name: 'EmailDestinatario',
    width: '2.0072992700729935%',
    widthDefault: '5.5%',
    orderable: false,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 26,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Grupo Destinatário',
    data: 'GrupoDestinatario',
    name: 'GrupoDestinatario',
    width: '2.0072992700729935%',
    widthDefault: '5.5%',
    orderable: true,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 27,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Categoria Destinatário',
    data: 'CategoriaDestinatario',
    name: 'CategoriaDestinatario',
    width: '2.0072992700729935%',
    widthDefault: '5.5%',
    orderable: true,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 28,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Restrições',
    data: 'Restricoes',
    name: 'Restricoes',
    width: '2.0072992700729935%',
    widthDefault: '5.5%',
    orderable: true,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 29,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Expedidor',
    data: 'NomeFantasiaExpedidor',
    name: 'NomeFantasiaExpedidor',
    width: '2.0072992700729935%',
    widthDefault: '5.5%',
    orderable: true,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 30,
    sumary: 0,
    enableGroup: true,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Código SAP Expedidor',
    data: 'CodigoSapExpedidor',
    name: 'CodigoSapExpedidor',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: true,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 31,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Origem',
    data: 'Origem',
    name: 'Origem',
    width: '1.0948905109489055%',
    widthDefault: '3%',
    orderable: true,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 32,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Destino',
    data: 'Destino',
    name: 'Destino',
    width: '1.0948905109489055%',
    widthDefault: '3%',
    orderable: true,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 33,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Grupo Pessoa',
    data: 'GrupoPessoa',
    name: 'GrupoPessoa',
    width: '2.0072992700729935%',
    widthDefault: '5.5%',
    orderable: true,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 34,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Nota Fiscal',
    data: 'NotasFiscais',
    name: 'NotasFiscais',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: true,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 35,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Série Nota Fiscal',
    data: 'SerieNotaFiscal',
    name: 'SerieNotaFiscal',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: true,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 36,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Chave NF-e',
    data: 'ChaveNFe',
    name: 'ChaveNFe',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: true,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 37,
    sumary: 0,
    enableGroup: true,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Valor NF-e',
    data: 'ValorNFe',
    name: 'ValorNFe',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: true,
    visible: true,
    className: 'text-end',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 38,
    sumary: 1,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Peso',
    data: 'Peso',
    name: 'Peso',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: true,
    visible: true,
    className: 'text-end',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 39,
    sumary: 1,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Vol.',
    data: 'Volumes',
    name: 'Volumes',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: true,
    visible: true,
    className: 'text-end',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 40,
    sumary: 1,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Número de Pallet',
    data: 'NumeroPallet',
    name: 'NumeroPallet',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: true,
    visible: true,
    className: 'text-end',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 41,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Frete Valor',
    data: 'Frete',
    name: 'Frete',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: true,
    visible: true,
    className: 'text-end',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 42,
    sumary: 1,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Valor dos Componentes',
    data: 'ValorComponentes',
    name: 'ValorComponentes',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: true,
    visible: true,
    className: 'text-end',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 43,
    sumary: 1,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Frete Total Sem Imposto',
    data: 'FreteTotalSemImposto',
    name: 'FreteTotalSemImposto',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: false,
    visible: true,
    className: 'text-end',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 44,
    sumary: 1,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Aliquota ICMS',
    data: 'AliquotaICMS',
    name: 'AliquotaICMS',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: false,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 45,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Valor ICMS',
    data: 'ICMS',
    name: 'ICMS',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: false,
    visible: true,
    className: 'text-end',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 46,
    sumary: 1,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Valor ICMS ST',
    data: 'ValorICMSST',
    name: 'ValorICMSST',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: false,
    visible: true,
    className: 'text-end',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 47,
    sumary: 1,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Valor ISS',
    data: 'ValorISS',
    name: 'ValorISS',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: false,
    visible: true,
    className: 'text-end',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 48,
    sumary: 1,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Aliquota ISS',
    data: 'AliquotaISS',
    name: 'AliquotaISS',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: false,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 49,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Valor ISS Retido',
    data: 'ValorISSRetido',
    name: 'ValorISSRetido',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: false,
    visible: true,
    className: 'text-end',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 50,
    sumary: 1,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Total a Receber',
    data: 'TotalReceber',
    name: 'TotalReceber',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: false,
    visible: true,
    className: 'text-end',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 51,
    sumary: 1,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'CST',
    data: 'CST',
    name: 'CST',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: false,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 52,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'CT-e',
    data: 'CTe',
    name: 'CTe',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: true,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 53,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Série CT-e',
    data: 'SerieCTe',
    name: 'SerieCTe',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: true,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 54,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Tipo CT-e',
    data: 'TipoCTeFormatado',
    name: 'TipoCTeFormatado',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: false,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 55,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'CFOP',
    data: 'CFOP',
    name: 'CFOP',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: true,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 56,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Frete Líquido',
    data: 'FreteTotalLiquidoCTe',
    name: 'FreteTotalLiquidoCTe',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: true,
    visible: true,
    className: 'text-end',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 57,
    sumary: 1,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Frete Total CT-e',
    data: 'FreteTotalCTe',
    name: 'FreteTotalCTe',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: true,
    visible: true,
    className: 'text-end',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 58,
    sumary: 1,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Valor do ICMS do CT-e',
    data: 'ValorICMS',
    name: 'ValorICMS',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: true,
    visible: true,
    className: 'text-end',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 59,
    sumary: 1,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Motorista',
    data: 'Motorista',
    name: 'Motorista',
    width: '2.0072992700729935%',
    widthDefault: '5.5%',
    orderable: false,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 60,
    sumary: 0,
    enableGroup: true,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Placa',
    data: 'Placa',
    name: 'Placa',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: false,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 61,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Capacidade Veículo',
    data: 'CapacidadeVeiculo',
    name: 'CapacidadeVeiculo',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: false,
    visible: true,
    className: 'text-end',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 62,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: 'n2',
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Metro Cúbico',
    data: 'MetroCubico',
    name: 'MetroCubico',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: false,
    visible: true,
    className: 'text-end',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 63,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Metro Cúbico NF-e',
    data: 'MetroCubicoNFe',
    name: 'MetroCubicoNFe',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: false,
    visible: true,
    className: 'text-end',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 64,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Qtd. Total Produto',
    data: 'QuantidadeTotalProduto',
    name: 'QuantidadeTotalProduto',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: true,
    visible: true,
    className: 'text-end',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 65,
    sumary: 1,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Valor Mercadoria CT-e',
    data: 'ValorMercadoriaTotalCTe',
    name: 'ValorMercadoriaTotalCTe',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: true,
    visible: true,
    className: 'text-end',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 66,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'CEP Destinatário',
    data: 'CEPDestinatario',
    name: 'CEPDestinatario',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: true,
    visible: true,
    className: 'text-end',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 67,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'País Destinatário',
    data: 'PaisDestinatario',
    name: 'PaisDestinatario',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: true,
    visible: true,
    className: 'text-end',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 68,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Previsão Entrega Pedido',
    data: 'PrevisaoEntregaPedido',
    name: 'PrevisaoEntregaPedido',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: true,
    visible: true,
    className: 'text-end',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 69,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Data Realizada Entrega',
    data: 'DataRealizadaEntrega',
    name: 'DataRealizadaEntrega',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: true,
    visible: true,
    className: 'text-end',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 70,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Atendimentos',
    data: 'Atendimentos',
    name: 'Atendimentos',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: true,
    visible: true,
    className: 'text-end',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 71,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Situação Nota Fiscal',
    data: 'SituacaoNotaFiscal',
    name: 'SituacaoNotaFiscal',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: true,
    visible: true,
    className: 'text-end',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 72,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Situação Entrega',
    data: 'DescricaoSituacaoEntrega',
    name: 'DescricaoSituacaoEntrega',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: true,
    visible: true,
    className: 'text-end',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 73,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'SLA Documento',
    data: 'SLADocumento',
    name: 'SLADocumento',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: true,
    visible: true,
    className: 'text-end',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 74,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Modelo Veicular',
    data: 'ModeloVeicular',
    name: 'ModeloVeicular',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: true,
    visible: true,
    className: 'text-end',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 75,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Nome Vendedor',
    data: 'NomeVendedor',
    name: 'NomeVendedor',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: true,
    visible: true,
    className: 'text-end',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 76,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Telefone Vendedor',
    data: 'TelefoneVendedor',
    name: 'TelefoneVendedor',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: true,
    visible: true,
    className: 'text-end',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 77,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'KM Filial/Cliente',
    data: 'KMFilialCliente',
    name: 'KMFilialCliente',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: true,
    visible: true,
    className: 'text-end',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 78,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Mês Previsão Entrega Pedido',
    data: 'MesPrevisaoEntregaPedido',
    name: 'MesPrevisaoEntregaPedido',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: true,
    visible: true,
    className: 'text-end',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 79,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Semana Previsão Entrega Pedido',
    data: 'SemanaPrevisaoEntregaPedido',
    name: 'SemanaPrevisaoEntregaPedido',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: true,
    visible: true,
    className: 'text-end',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 80,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Número Remessa Espelho',
    data: 'NumeroRemessaEspelho',
    name: 'NumeroRemessaEspelho',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: false,
    visible: true,
    className: 'text-end',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 81,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Quantidade Volumes',
    data: 'QuantidadeVolumes',
    name: 'QuantidadeVolumes',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: false,
    visible: true,
    className: 'text-end',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 82,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Classificação NFe',
    data: 'ClassificacaoNFeDescricao',
    name: 'ClassificacaoNFeDescricao',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: false,
    visible: true,
    className: 'text-end',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 83,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Nº do Pedido Cliente',
    data: 'NumeroPedidoCliente',
    name: 'NumeroPedidoCliente',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: false,
    visible: true,
    className: 'text-end',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 84,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Data Início Viagem',
    data: 'DataInicioViagemFormatada',
    name: 'DataInicioViagemFormatada',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: false,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 85,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Situação da Carga',
    data: 'DescricaoSituacao',
    name: 'DescricaoSituacao',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: true,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 86,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Data Situação Nota Fiscal Entrega',
    data: 'DataSituacaoNotaFiscalEntregaFormatada',
    name: 'DataSituacaoNotaFiscalEntregaFormatada',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: true,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 87,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Situação Nota Fiscal Entrega',
    data: 'DescricaoSituacaoNotaFiscalEntrega',
    name: 'DescricaoSituacaoNotaFiscalEntrega',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: true,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 88,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Observação',
    data: 'ObservacaoPedido',
    name: 'ObservacaoPedido',
    width: '2.0072992700729935%',
    widthDefault: '5.5%',
    orderable: false,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 89,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Quantidade de peças',
    data: 'QuantidadePecas',
    name: 'QuantidadePecas',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: false,
    visible: true,
    className: 'text-end',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 90,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'ID Agrupador',
    data: 'IdAgrupador',
    name: 'IdAgrupador',
    width: '1.0948905109489055%',
    widthDefault: '3%',
    orderable: false,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 91,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Código SAP Destinatário',
    data: 'CodigoSAPDestinatario',
    name: 'CodigoSAPDestinatario',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: false,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 92,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Nº Destino',
    data: 'NumeroDestino',
    name: 'NumeroDestino',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: false,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 93,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'UF Origem',
    data: 'UFOrigem',
    name: 'UFOrigem',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: false,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 94,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'UF Destino',
    data: 'UFDestino',
    name: 'UFDestino',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: false,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 95,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Data da Entrega',
    data: 'DataEntregaFormatada',
    name: 'DataEntregaFormatada',
    width: '1.0948905109489055%',
    widthDefault: '3%',
    orderable: false,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 96,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Data Prevista Carga Entrega',
    data: 'DataPrevisaoCargaEntregaFormatada',
    name: 'DataPrevisaoCargaEntregaFormatada',
    width: '1.0948905109489055%',
    widthDefault: '3%',
    orderable: false,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 97,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Natureza Nota Fiscal',
    data: 'NaturezaOP',
    name: 'NaturezaOP',
    width: '1.0948905109489055%',
    widthDefault: '3%',
    orderable: false,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 98,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Expedidor Carga',
    data: 'ExpedidorCarga',
    name: 'ExpedidorCarga',
    width: '1.0948905109489055%',
    widthDefault: '3%',
    orderable: false,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 99,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Recebedor Carga',
    data: 'RecebedorCarga',
    name: 'RecebedorCarga',
    width: '1.0948905109489055%',
    widthDefault: '3%',
    orderable: false,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 100,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Codigo Integração Migo',
    data: 'CodigoInteragracaoMigo',
    name: 'CodigoInteragracaoMigo',
    width: '1.0948905109489055%',
    widthDefault: '3%',
    orderable: false,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 101,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Data Integração Migo',
    data: 'DataMigoFormatado',
    name: 'DataMigoFormatado',
    width: '1.0948905109489055%',
    widthDefault: '3%',
    orderable: false,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 102,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Codigo Integração Miro',
    data: 'CodigoInteragracaoMiro',
    name: 'CodigoInteragracaoMiro',
    width: '1.0948905109489055%',
    widthDefault: '3%',
    orderable: false,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 103,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Data Integração Miro',
    data: 'DataMiroFormatado',
    name: 'DataMiroFormatado',
    width: '1.0948905109489055%',
    widthDefault: '3%',
    orderable: false,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 104,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Transbordo',
    data: 'Transbordo',
    name: 'Transbordo',
    width: '1.0948905109489055%',
    widthDefault: '3%',
    orderable: false,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 105,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Peso Líquido',
    data: 'PesoLiquido',
    name: 'PesoLiquido',
    width: '1.0948905109489055%',
    widthDefault: '3%',
    orderable: false,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 106,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Número Pedido NFe',
    data: 'NumeroPedidoNFe',
    name: 'NumeroPedidoNFe',
    width: '1.0948905109489055%',
    widthDefault: '3%',
    orderable: false,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 107,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
  {
    title: 'Fatura',
    data: 'Fatura',
    name: 'Fatura',
    width: '0.6386861313868616%',
    widthDefault: '1.75%',
    orderable: true,
    visible: true,
    className: 'text-start',
    dateTimePattern: 'dd/MM/yyyy HH:mm:ss',
    tabletHide: false,
    phoneHide: false,
    position: 108,
    sumary: 0,
    enableGroup: false,
    dynamicCode: 0,
    decimalPrecision: 0,
    dataTypeExportacao: '',
    editableCell: {
      editable: false,
      type: 0,
      mask: null,
      maxlength: 0,
      numberMask: {
        allowZero: false,
        precision: 0,
        thousandsSeparator: true,
      },
      precisionDecimal: 0,
    },
    insertInGroupByWhenInvisible: false,
    numberFormat: null,
    useTextFormat: false,
    tabName: '',
  },
];
